"""test

Revision ID: 3a4ddb95c1f2
Revises: 
Create Date: 2017-08-28 13:20:01.833334+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a4ddb95c1f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'users', sa.Column('accredit', sa.String(length=100), nullable=True))
    op.add_column(u'users', sa.Column('accredit_own', sa.String(length=100), nullable=True))
    op.add_column(u'users', sa.Column('cur_login_at', sa.DateTime(), nullable=True))
    op.add_column(u'users', sa.Column('is_superadmin', sa.SmallInteger(), nullable=False))
    op.add_column(u'users', sa.Column('last_action_at', sa.DateTime(), nullable=True))
    op.add_column(u'users', sa.Column('last_email_no_servers_sent_at', sa.DateTime(), nullable=True))
    op.add_column(u'users', sa.Column('last_email_report_enqueued_at', sa.DateTime(), nullable=True))
    op.add_column(u'users', sa.Column('last_email_report_sent_at', sa.DateTime(), nullable=True))
    op.add_column(u'users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column(u'users', sa.Column('last_login_id', mysql.INTEGER(display_width=10, unsigned=True), nullable=True))
    op.add_column(u'users', sa.Column('timezone', sa.String(length=191), nullable=True))
    op.add_column(u'users', sa.Column('utc_offset', sa.Integer(), nullable=False))
    op.add_column(u'users', sa.Column('weekly_emails_disabled', sa.SmallInteger(), nullable=False))

    op.add_column(u'scan_jobs', sa.Column('crtsh_check_id', sa.BigInteger(), nullable=True))
    op.add_column(u'scan_jobs', sa.Column('crtsh_checks', sa.String(length=255), nullable=True))
    op.add_column(u'scan_jobs', sa.Column('dns_check_id', sa.BigInteger(), nullable=True))
    op.add_column(u'scan_jobs', sa.Column('scan_ip', sa.String(length=255), nullable=True))
    op.add_column(u'scan_jobs', sa.Column('whois_check_id', sa.BigInteger(), nullable=True))
    op.alter_column(u'scan_jobs', 'scan_host',
                    existing_type=mysql.VARCHAR(collation=u'utf8mb4_unicode_ci', length=191),
                    nullable=True)


    op.create_table('alembic_version_data',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('schema_ver', sa.BigInteger(), nullable=True),
                    sa.Column('data_ver', sa.BigInteger(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('base_domain',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('domain_name', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('domain_name')
                    )

    op.create_table('certificates',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('crt_sh_id', sa.BigInteger(), nullable=True),
                    sa.Column('crt_sh_ca_id', sa.BigInteger(), nullable=True),
                    sa.Column('fprint_sha1', sa.String(length=40), nullable=False),
                    sa.Column('fprint_sha256', sa.String(length=64), nullable=True),
                    sa.Column('valid_from', sa.DateTime(), nullable=True),
                    sa.Column('valid_to', sa.DateTime(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('cname', sa.Text(), nullable=True),
                    sa.Column('subject', sa.Text(), nullable=True),
                    sa.Column('issuer', sa.Text(), nullable=True),
                    sa.Column('is_ca', sa.SmallInteger(), nullable=False),
                    sa.Column('is_self_signed', sa.SmallInteger(), nullable=False),
                    sa.Column('is_precert', sa.SmallInteger(), nullable=False),
                    sa.Column('is_precert_ca', sa.SmallInteger(), nullable=False),
                    sa.Column('parent_id', sa.BigInteger(), nullable=True),
                    sa.Column('is_le', sa.SmallInteger(), nullable=False),
                    sa.Column('is_cloudflare', sa.SmallInteger(), nullable=False),
                    sa.Column('key_type', sa.SmallInteger(), nullable=True),
                    sa.Column('key_bit_size', sa.Integer(), nullable=True),
                    sa.Column('sig_alg', sa.Integer(), nullable=True),
                    sa.Column('alt_names', sa.Text(), nullable=True),
                    sa.Column('source', sa.String(length=255), nullable=True),
                    sa.Column('pem', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('fprint_sha1', name='crt_fprint_sha1_uniqe')
                    )
    op.create_index(op.f('ix_certificates_crt_sh_id'), 'certificates', ['crt_sh_id'], unique=False)
    op.create_index(op.f('ix_certificates_fprint_sha1'), 'certificates', ['fprint_sha1'], unique=False)
    op.create_index(op.f('ix_certificates_fprint_sha256'), 'certificates', ['fprint_sha256'], unique=False)

    op.create_table('certificate_alt_names',
                    sa.Column('cert_id', sa.BigInteger(), nullable=False),
                    sa.Column('alt_name', sa.String(length=255), nullable=False),
                    sa.Column('is_wildcard', sa.SmallInteger(), nullable=False),
                    sa.PrimaryKeyConstraint('cert_id', 'alt_name', 'is_wildcard')
                    )
    op.create_index(op.f('ix_certificate_alt_names_alt_name'), 'certificate_alt_names', ['alt_name'], unique=False)
    op.create_index(op.f('ix_certificate_alt_names_cert_id'), 'certificate_alt_names', ['cert_id'], unique=False)

    op.create_table('domain_name',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('domain_name', sa.String(length=255), nullable=False),
                    sa.Column('top_domain_id', sa.BigInteger(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('domain_name')
                    )
    op.create_index(op.f('ix_domain_name_top_domain_id'), 'domain_name', ['top_domain_id'], unique=False)

    op.create_table('email_news',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('schedule_at', sa.DateTime(), nullable=True),
                    sa.Column('valid_to', sa.DateTime(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('disabled_at', sa.DateTime(), nullable=True),
                    sa.Column('message', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('email_news_user',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('user_id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
                    sa.Column('email_news_id', sa.BigInteger(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_email_news_user_email_news_id'), 'email_news_user', ['email_news_id'], unique=False)
    op.create_index(op.f('ix_email_news_user_user_id'), 'email_news_user', ['user_id'], unique=False)
    op.create_table('ip_address',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('ip_addr', sa.String(length=255), nullable=False),
                    sa.Column('ip_type', sa.SmallInteger(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('ip_addr')
                    )

    op.create_table('crtsh_input',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('sld_id', sa.BigInteger(), nullable=True),
                    sa.Column('iquery', sa.String(length=255), nullable=False),
                    sa.Column('itype', sa.SmallInteger(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('iquery', 'itype', name='crtsh_input_key_unique')
                    )
    op.create_index(op.f('ix_crtsh_input_sld_id'), 'crtsh_input', ['sld_id'], unique=False)

    op.create_table('crtsh_query',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('job_id', sa.BigInteger(), nullable=True),
                    sa.Column('watch_id', sa.BigInteger(), nullable=True),
                    sa.Column('input_id', sa.BigInteger(), nullable=True),
                    sa.Column('sub_watch_id', sa.BigInteger(), nullable=True),
                    sa.Column('service_id', sa.BigInteger(), nullable=True),
                    sa.Column('last_scan_at', sa.DateTime(), nullable=True),
                    sa.Column('num_scans', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('status', sa.SmallInteger(), nullable=True),
                    sa.Column('results', sa.Integer(), nullable=True),
                    sa.Column('new_results', sa.Integer(), nullable=True),
                    sa.Column('newest_cert_id', sa.BigInteger(), nullable=True),
                    sa.Column('newest_cert_sh_id', sa.BigInteger(), nullable=True),
                    sa.Column('certs_ids', sa.Text(), nullable=True),
                    sa.Column('certs_sh_ids', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_crtsh_query_input_id'), 'crtsh_query', ['input_id'], unique=False)
    op.create_index(op.f('ix_crtsh_query_service_id'), 'crtsh_query', ['service_id'], unique=False)
    op.create_index(op.f('ix_crtsh_query_sub_watch_id'), 'crtsh_query', ['sub_watch_id'], unique=False)
    op.create_index(op.f('ix_crtsh_query_watch_id'), 'crtsh_query', ['watch_id'], unique=False)

    op.create_table('crtsh_query_results',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('query_id', sa.BigInteger(), nullable=True),
                    sa.Column('job_id', sa.BigInteger(), nullable=True),
                    sa.Column('crt_id', sa.BigInteger(), nullable=True),
                    sa.Column('crt_sh_id', sa.BigInteger(), nullable=True),
                    sa.Column('was_new', sa.SmallInteger(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_crtsh_query_results_query_id'), 'crtsh_query_results', ['query_id'], unique=False)



    op.create_table('ip_scan_record',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('service_name', sa.String(length=255), nullable=False),
                    sa.Column('service_id', sa.BigInteger(), nullable=True),
                    sa.Column('ip_beg', sa.String(length=24), nullable=False),
                    sa.Column('ip_end', sa.String(length=24), nullable=False),
                    sa.Column('ip_beg_int', sa.BigInteger(), nullable=True),
                    sa.Column('ip_end_int', sa.BigInteger(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('last_scan_at', sa.DateTime(), nullable=True),
                    sa.Column('last_scan_state', sa.SmallInteger(), nullable=True),
                    sa.Column('num_scans', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_ip_scan_record_service_id'), 'ip_scan_record', ['service_id'], unique=False)
    op.create_table('ip_scan_result',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('ip_scan_record_id', sa.BigInteger(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('finished_at', sa.DateTime(), nullable=True),
                    sa.Column('duration', sa.BigInteger(), nullable=True),
                    sa.Column('last_scan_at', sa.DateTime(), nullable=True),
                    sa.Column('last_scan_state', sa.SmallInteger(), nullable=True),
                    sa.Column('num_scans', sa.Integer(), nullable=True),
                    sa.Column('num_ips_alive', sa.Integer(), nullable=False),
                    sa.Column('num_ips_found', sa.Integer(), nullable=False),
                    sa.Column('ips_alive', sa.Text(), nullable=True),
                    sa.Column('ips_found', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_ip_scan_result_ip_scan_record_id'), 'ip_scan_result', ['ip_scan_record_id'], unique=False)
    op.create_table('keychest_agent',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('name', sa.String(length=191), nullable=False),
                    sa.Column('api_key', sa.String(length=191), nullable=False),
                    sa.Column('organization_id', sa.BigInteger(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('last_seen_active_at', sa.DateTime(), nullable=True),
                    sa.Column('last_seen_ip', sa.String(length=191), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_keychest_agent_api_key'), 'keychest_agent', ['api_key'], unique=False)
    op.create_index(op.f('ix_keychest_agent_organization_id'), 'keychest_agent', ['organization_id'], unique=False)
    op.create_table('last_scan_cache',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('cache_type', sa.SmallInteger(), nullable=False),
                    sa.Column('obj_id', sa.BigInteger(), nullable=True),
                    sa.Column('scan_type', sa.Integer(), nullable=False),
                    sa.Column('scan_sub_type', sa.Integer(), nullable=False),
                    sa.Column('aux_key', sa.String(length=191), nullable=False),
                    sa.Column('scan_id', sa.BigInteger(), nullable=False),
                    sa.Column('scan_aux', sa.Text(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('cache_type', 'obj_id', 'scan_type', 'scan_sub_type', 'aux_key',
                                        name='uq_last_scan_cache_key')
                    )
    op.create_index(op.f('ix_last_scan_cache_obj_id'), 'last_scan_cache', ['obj_id'], unique=False)
    op.create_index(op.f('ix_last_scan_cache_scan_type'), 'last_scan_cache', ['scan_type'], unique=False)
    op.create_table('organization',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('name', sa.String(length=191), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('organization_group',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('name', sa.String(length=191), nullable=False),
                    sa.Column('organization_id', sa.BigInteger(), nullable=False),
                    sa.Column('parent_group_id', sa.BigInteger(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_organization_group_organization_id'), 'organization_group', ['organization_id'],
                    unique=False)
    op.create_index(op.f('ix_organization_group_parent_group_id'), 'organization_group', ['parent_group_id'],
                    unique=False)
    op.create_table('scan_dns',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('job_id', sa.BigInteger(), nullable=True),
                    sa.Column('watch_id', sa.BigInteger(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('last_scan_at', sa.DateTime(), nullable=True),
                    sa.Column('num_scans', sa.Integer(), nullable=True),
                    sa.Column('status', sa.SmallInteger(), nullable=True),
                    sa.Column('num_res', sa.SmallInteger(), nullable=False),
                    sa.Column('num_ipv4', sa.SmallInteger(), nullable=False),
                    sa.Column('num_ipv6', sa.SmallInteger(), nullable=False),
                    sa.Column('is_synthetic', sa.SmallInteger(), nullable=False),
                    sa.Column('dns', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_scan_dns_watch_id'), 'scan_dns', ['watch_id'], unique=False)
    op.create_table('scan_dns_entry',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('scan_id', sa.BigInteger(), nullable=False),
                    sa.Column('is_ipv6', sa.SmallInteger(), nullable=False),
                    sa.Column('is_internal', sa.SmallInteger(), nullable=False),
                    sa.Column('ip', sa.String(length=191), nullable=False),
                    sa.Column('res_order', sa.SmallInteger(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_scan_dns_entry_ip'), 'scan_dns_entry', ['ip'], unique=False)
    op.create_index(op.f('ix_scan_dns_entry_scan_id'), 'scan_dns_entry', ['scan_id'], unique=False)
    op.create_table('scan_gaps',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('watch_id', sa.BigInteger(), nullable=True),
                    sa.Column('scan_code', sa.SmallInteger(), nullable=False),
                    sa.Column('scan_type', sa.SmallInteger(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('gap_start', sa.DateTime(), nullable=True),
                    sa.Column('gap_end', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_scan_gaps_watch_id'), 'scan_gaps', ['watch_id'], unique=False)
    op.create_table('scan_handshake_results',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('scan_id', sa.BigInteger(), nullable=True),
                    sa.Column('job_id', sa.BigInteger(), nullable=True),
                    sa.Column('crt_id', sa.BigInteger(), nullable=True),
                    sa.Column('crt_sh_id', sa.BigInteger(), nullable=True),
                    sa.Column('was_new', sa.SmallInteger(), nullable=True),
                    sa.Column('is_ca', sa.SmallInteger(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_scan_handshake_results_scan_id'), 'scan_handshake_results', ['scan_id'], unique=False)
    op.create_table('scan_handshakes',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('job_id', sa.BigInteger(), nullable=True),
                    sa.Column('watch_id', sa.BigInteger(), nullable=True),
                    sa.Column('ip_scanned', sa.String(length=255), nullable=True),
                    sa.Column('is_ipv6', sa.SmallInteger(), nullable=False),
                    sa.Column('tls_ver', sa.String(length=16), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('last_scan_at', sa.DateTime(), nullable=True),
                    sa.Column('num_scans', sa.Integer(), nullable=True),
                    sa.Column('status', sa.SmallInteger(), nullable=True),
                    sa.Column('err_code', sa.SmallInteger(), nullable=True),
                    sa.Column('tls_alert_code', sa.Integer(), nullable=True),
                    sa.Column('time_elapsed', sa.Integer(), nullable=True),
                    sa.Column('results', sa.Integer(), nullable=True),
                    sa.Column('new_results', sa.Integer(), nullable=True),
                    sa.Column('certs_ids', sa.Text(), nullable=True),
                    sa.Column('cert_id_leaf', sa.BigInteger(), nullable=True),
                    sa.Column('valid_path', sa.SmallInteger(), nullable=True),
                    sa.Column('valid_hostname', sa.SmallInteger(), nullable=True),
                    sa.Column('err_validity', sa.String(length=64), nullable=True),
                    sa.Column('err_many_leafs', sa.SmallInteger(), nullable=True),
                    sa.Column('err_valid_ossl_code', sa.Integer(), nullable=True),
                    sa.Column('err_valid_ossl_depth', sa.Integer(), nullable=True),
                    sa.Column('sub_rsa', sa.BigInteger(), nullable=True),
                    sa.Column('sub_ecc', sa.BigInteger(), nullable=True),
                    sa.Column('req_https_result', sa.String(length=64), nullable=True),
                    sa.Column('follow_http_result', sa.String(length=64), nullable=True),
                    sa.Column('follow_https_result', sa.String(length=64), nullable=True),
                    sa.Column('follow_http_url', sa.String(length=255), nullable=True),
                    sa.Column('follow_https_url', sa.String(length=255), nullable=True),
                    sa.Column('hsts_present', sa.SmallInteger(), nullable=True),
                    sa.Column('hsts_max_age', sa.BigInteger(), nullable=True),
                    sa.Column('hsts_include_subdomains', sa.SmallInteger(), nullable=True),
                    sa.Column('hsts_preload', sa.SmallInteger(), nullable=True),
                    sa.Column('pinning_present', sa.SmallInteger(), nullable=True),
                    sa.Column('pinning_report_only', sa.SmallInteger(), nullable=True),
                    sa.Column('pinning_pins', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_scan_handshakes_sub_ecc'), 'scan_handshakes', ['sub_ecc'], unique=False)
    op.create_index(op.f('ix_scan_handshakes_sub_rsa'), 'scan_handshakes', ['sub_rsa'], unique=False)
    op.create_index(op.f('ix_scan_handshakes_watch_id'), 'scan_handshakes', ['watch_id'], unique=False)
    op.create_table('scan_history',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('watch_id', sa.BigInteger(), nullable=True),
                    sa.Column('scan_code', sa.SmallInteger(), nullable=False),
                    sa.Column('scan_type', sa.SmallInteger(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_scan_history_watch_id'), 'scan_history', ['watch_id'], unique=False)
    op.create_table('scan_sub_tls',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('job_id', sa.BigInteger(), nullable=True),
                    sa.Column('watch_id', sa.BigInteger(), nullable=True),
                    sa.Column('parent_scan_id', sa.BigInteger(), nullable=True),
                    sa.Column('ip_scanned', sa.String(length=255), nullable=True),
                    sa.Column('is_ipv6', sa.SmallInteger(), nullable=False),
                    sa.Column('tls_ver', sa.String(length=16), nullable=True),
                    sa.Column('key_type', sa.SmallInteger(), nullable=True),
                    sa.Column('cipersuite_set', sa.BigInteger(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('last_scan_at', sa.DateTime(), nullable=True),
                    sa.Column('num_scans', sa.Integer(), nullable=True),
                    sa.Column('status', sa.SmallInteger(), nullable=True),
                    sa.Column('err_code', sa.SmallInteger(), nullable=True),
                    sa.Column('tls_alert_code', sa.Integer(), nullable=True),
                    sa.Column('time_elapsed', sa.Integer(), nullable=True),
                    sa.Column('results', sa.Integer(), nullable=True),
                    sa.Column('new_results', sa.Integer(), nullable=True),
                    sa.Column('certs_ids', sa.Text(), nullable=True),
                    sa.Column('cert_id_leaf', sa.BigInteger(), nullable=True),
                    sa.Column('valid_path', sa.SmallInteger(), nullable=True),
                    sa.Column('valid_hostname', sa.SmallInteger(), nullable=True),
                    sa.Column('err_validity', sa.String(length=64), nullable=True),
                    sa.Column('err_many_leafs', sa.SmallInteger(), nullable=True),
                    sa.Column('err_valid_ossl_code', sa.Integer(), nullable=True),
                    sa.Column('err_valid_ossl_depth', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_scan_sub_tls_parent_scan_id'), 'scan_sub_tls', ['parent_scan_id'], unique=False)
    op.create_index(op.f('ix_scan_sub_tls_watch_id'), 'scan_sub_tls', ['watch_id'], unique=False)
    op.create_table('scan_tls_desc',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('ip_id', sa.BigInteger(), nullable=False),
                    sa.Column('sni_id', sa.BigInteger(), nullable=False),
                    sa.Column('scan_port', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('ip_id', 'sni_id', 'scan_port', name='uk_scan_tls_desc_unique')
                    )
    op.create_index(op.f('ix_scan_tls_desc_ip_id'), 'scan_tls_desc', ['ip_id'], unique=False)
    op.create_index(op.f('ix_scan_tls_desc_sni_id'), 'scan_tls_desc', ['sni_id'], unique=False)
    op.create_table('scan_tls_desc_ext',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('tls_desc_id', sa.BigInteger(), nullable=False),
                    sa.Column('tls_params_id', sa.BigInteger(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('tls_desc_id', 'tls_params_id', name='uk_scan_tls_desc_ext_unique')
                    )
    op.create_index(op.f('ix_scan_tls_desc_ext_tls_desc_id'), 'scan_tls_desc_ext', ['tls_desc_id'], unique=False)
    op.create_index(op.f('ix_scan_tls_desc_ext_tls_params_id'), 'scan_tls_desc_ext', ['tls_params_id'], unique=False)
    op.create_table('scan_tls_params',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('tls_ver', sa.String(length=16), nullable=True),
                    sa.Column('key_type', sa.SmallInteger(), nullable=True),
                    sa.Column('cipersuite_set', sa.BigInteger(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('tls_ver', 'key_type', 'cipersuite_set', name='uk_scan_tls_params_unique')
                    )
    op.create_table('scan_web_app',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('host_id', sa.BigInteger(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('last_scan_at', sa.DateTime(), nullable=True),
                    sa.Column('num_scans', sa.Integer(), nullable=True),
                    sa.Column('req_https_result', sa.String(length=64), nullable=True),
                    sa.Column('follow_http_result', sa.String(length=64), nullable=True),
                    sa.Column('follow_https_result', sa.String(length=64), nullable=True),
                    sa.Column('follow_http_url', sa.String(length=255), nullable=True),
                    sa.Column('follow_https_url', sa.String(length=255), nullable=True),
                    sa.Column('hsts_present', sa.SmallInteger(), nullable=True),
                    sa.Column('hsts_max_age', sa.BigInteger(), nullable=True),
                    sa.Column('hsts_include_subdomains', sa.SmallInteger(), nullable=True),
                    sa.Column('hsts_preload', sa.SmallInteger(), nullable=True),
                    sa.Column('pinning_present', sa.SmallInteger(), nullable=True),
                    sa.Column('pinning_report_only', sa.SmallInteger(), nullable=True),
                    sa.Column('pinning_pins', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_scan_web_app_host_id'), 'scan_web_app', ['host_id'], unique=False)
    op.create_table('subdomain_results',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('watch_id', sa.BigInteger(), nullable=False),
                    sa.Column('scan_type', sa.SmallInteger(), nullable=True),
                    sa.Column('scan_status', sa.SmallInteger(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('last_scan_at', sa.DateTime(), nullable=True),
                    sa.Column('last_scan_idx', sa.BigInteger(), nullable=True),
                    sa.Column('num_scans', sa.Integer(), nullable=True),
                    sa.Column('result_size', sa.Integer(), nullable=False),
                    sa.Column('result', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_subdomain_results_watch_id'), 'subdomain_results', ['watch_id'], unique=False)
    op.create_table('subdomain_scan_blacklist',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('rule', sa.String(length=255), nullable=False),
                    sa.Column('rule_type', sa.SmallInteger(), nullable=True),
                    sa.Column('detection_code', sa.SmallInteger(), nullable=True),
                    sa.Column('detection_value', sa.Integer(), nullable=True),
                    sa.Column('detection_first_at', sa.DateTime(), nullable=True),
                    sa.Column('detection_last_at', sa.DateTime(), nullable=True),
                    sa.Column('detection_num', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('subdomain_watch_result_entry',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('watch_id', sa.BigInteger(), nullable=False),
                    sa.Column('service_id', sa.BigInteger(), nullable=True),
                    sa.Column('is_wildcard', sa.SmallInteger(), nullable=False),
                    sa.Column('is_internal', sa.SmallInteger(), nullable=False),
                    sa.Column('is_long', sa.SmallInteger(), nullable=False),
                    sa.Column('name', sa.String(length=191), nullable=False),
                    sa.Column('name_full', sa.Text(), nullable=True),
                    sa.Column('res_order', sa.SmallInteger(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('last_scan_at', sa.DateTime(), nullable=True),
                    sa.Column('num_scans', sa.Integer(), nullable=False),
                    sa.Column('last_scan_id', sa.BigInteger(), nullable=True),
                    sa.Column('first_scan_id', sa.BigInteger(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_subdomain_watch_result_entry_first_scan_id'), 'subdomain_watch_result_entry',
                    ['first_scan_id'], unique=False)
    op.create_index(op.f('ix_subdomain_watch_result_entry_last_scan_id'), 'subdomain_watch_result_entry',
                    ['last_scan_id'], unique=False)
    op.create_index(op.f('ix_subdomain_watch_result_entry_name'), 'subdomain_watch_result_entry', ['name'],
                    unique=False)
    op.create_index(op.f('ix_subdomain_watch_result_entry_service_id'), 'subdomain_watch_result_entry', ['service_id'],
                    unique=False)
    op.create_index(op.f('ix_subdomain_watch_result_entry_watch_id'), 'subdomain_watch_result_entry', ['watch_id'],
                    unique=False)
    op.create_table('subdomain_watch_target',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('scan_host', sa.String(length=255), nullable=False),
                    sa.Column('scan_ports', sa.Text(), nullable=True),
                    sa.Column('top_domain_id', sa.BigInteger(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('last_scan_at', sa.DateTime(), nullable=True),
                    sa.Column('last_scan_state', sa.SmallInteger(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_subdomain_watch_target_top_domain_id'), 'subdomain_watch_target', ['top_domain_id'],
                    unique=False)
    op.create_table('system_last_events',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('event_key', sa.String(length=191), nullable=False),
                    sa.Column('event_at', sa.DateTime(), nullable=True),
                    sa.Column('aux', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('event_key')
                    )
    op.create_table('user_ip_scan_record',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('user_id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
                    sa.Column('ip_scan_record_id', sa.BigInteger(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('disabled_at', sa.DateTime(), nullable=True),
                    sa.Column('scan_periodicity', sa.BigInteger(), nullable=True),
                    sa.Column('auto_fill_watches', sa.SmallInteger(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('user_id', 'ip_scan_record_id', name='uk_user_ip_scan_record_unique')
                    )
    op.create_index(op.f('ix_user_ip_scan_record_ip_scan_record_id'), 'user_ip_scan_record', ['ip_scan_record_id'],
                    unique=False)
    op.create_index(op.f('ix_user_ip_scan_record_user_id'), 'user_ip_scan_record', ['user_id'], unique=False)
    op.create_table('user_login_history',
                    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
                    sa.Column('user_id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('login_at', sa.DateTime(), nullable=True),
                    sa.Column('login_ip', sa.String(length=191), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_login_history_user_id'), 'user_login_history', ['user_id'], unique=False)
    op.create_table('user_subdomain_watch_target',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('user_id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
                    sa.Column('watch_id', sa.BigInteger(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('disabled_at', sa.DateTime(), nullable=True),
                    sa.Column('auto_scan_added_at', sa.DateTime(), nullable=True),
                    sa.Column('scan_periodicity', sa.BigInteger(), nullable=True),
                    sa.Column('scan_type', sa.Integer(), nullable=True),
                    sa.Column('auto_fill_watches', sa.SmallInteger(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('user_id', 'watch_id', name='wa_user_sub_watcher_uniqe')
                    )
    op.create_index(op.f('ix_user_subdomain_watch_target_user_id'), 'user_subdomain_watch_target', ['user_id'],
                    unique=False)
    op.create_index(op.f('ix_user_subdomain_watch_target_watch_id'), 'user_subdomain_watch_target', ['watch_id'],
                    unique=False)
    op.create_table('user_watch_target',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('user_id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
                    sa.Column('watch_id', sa.BigInteger(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('disabled_at', sa.DateTime(), nullable=True),
                    sa.Column('auto_scan_added_at', sa.DateTime(), nullable=True),
                    sa.Column('scan_periodicity', sa.BigInteger(), nullable=True),
                    sa.Column('scan_type', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('user_id', 'watch_id', name='wa_user_watcher_uniqe')
                    )
    op.create_index(op.f('ix_user_watch_target_user_id'), 'user_watch_target', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_watch_target_watch_id'), 'user_watch_target', ['watch_id'], unique=False)
    op.create_table('watch_local_service',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('service_id', sa.BigInteger(), nullable=False),
                    sa.Column('agent_id', sa.BigInteger(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_watch_local_service_agent_id'), 'watch_local_service', ['agent_id'], unique=False)
    op.create_index(op.f('ix_watch_local_service_service_id'), 'watch_local_service', ['service_id'], unique=False)
    op.create_table('watch_service',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('service_name', sa.String(length=255), nullable=False),
                    sa.Column('top_domain_id', sa.BigInteger(), nullable=True),
                    sa.Column('crtsh_input_id', sa.BigInteger(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('last_scan_at', sa.DateTime(), nullable=True),
                    sa.Column('last_scan_state', sa.SmallInteger(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('service_name')
                    )

    op.create_index(op.f('ix_watch_service_crtsh_input_id'), 'watch_service', ['crtsh_input_id'], unique=False)
    op.create_index(op.f('ix_watch_service_top_domain_id'), 'watch_service', ['top_domain_id'], unique=False)
    op.create_table('watch_target',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('scan_host', sa.String(length=255), nullable=False),
                    sa.Column('scan_scheme', sa.String(length=255), nullable=True),
                    sa.Column('scan_port', sa.String(length=255), nullable=True),
                    sa.Column('scan_connect', sa.SmallInteger(), nullable=False),
                    sa.Column('is_ip_host', sa.SmallInteger(), nullable=False),
                    sa.Column('manual_dns', sa.SmallInteger(), nullable=False),
                    sa.Column('service_id', sa.BigInteger(), nullable=True),
                    sa.Column('top_domain_id', sa.BigInteger(), nullable=True),
                    sa.Column('agent_id', sa.BigInteger(), nullable=True),
                    sa.Column('ip_scan_id', sa.BigInteger(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('last_scan_at', sa.DateTime(), nullable=True),
                    sa.Column('last_scan_state', sa.SmallInteger(), nullable=False),
                    sa.Column('last_dns_scan_id', sa.BigInteger(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_watch_target_agent_id'), 'watch_target', ['agent_id'], unique=False)
    op.create_index(op.f('ix_watch_target_ip_scan_id'), 'watch_target', ['ip_scan_id'], unique=False)
    op.create_index(op.f('ix_watch_target_last_dns_scan_id'), 'watch_target', ['last_dns_scan_id'], unique=False)
    op.create_index(op.f('ix_watch_target_service_id'), 'watch_target', ['service_id'], unique=False)
    op.create_index(op.f('ix_watch_target_top_domain_id'), 'watch_target', ['top_domain_id'], unique=False)
    op.create_table('whois_result',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('domain_id', sa.BigInteger(), nullable=False),
                    sa.Column('status', sa.SmallInteger(), nullable=True),
                    sa.Column('registrant_cc', sa.String(length=255), nullable=True),
                    sa.Column('registrar', sa.String(length=255), nullable=True),
                    sa.Column('registered_at', sa.DateTime(), nullable=True),
                    sa.Column('expires_at', sa.DateTime(), nullable=True),
                    sa.Column('dnssec', sa.SmallInteger(), nullable=True),
                    sa.Column('rec_updated_at', sa.DateTime(), nullable=True),
                    sa.Column('dns', sa.Text(), nullable=True),
                    sa.Column('emails', sa.Text(), nullable=True),
                    sa.Column('aux', sa.Text(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('last_scan_at', sa.DateTime(), nullable=True),
                    sa.Column('num_scans', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_whois_result_domain_id'), 'whois_result', ['domain_id'], unique=False)
    op.create_index(op.f('ix_scan_jobs_crtsh_check_id'), 'scan_jobs', ['crtsh_check_id'], unique=False)
    op.create_index(op.f('ix_scan_jobs_dns_check_id'), 'scan_jobs', ['dns_check_id'], unique=False)
    op.create_index(op.f('ix_scan_jobs_whois_check_id'), 'scan_jobs', ['whois_check_id'], unique=False)

    op.create_foreign_key('sjob_crtsh_query_id', 'scan_jobs', 'crtsh_query', ['crtsh_check_id'], ['id'],
                          ondelete='SET NULL')
    op.create_foreign_key('sjob_whois_result_id', 'scan_jobs', 'whois_result', ['whois_check_id'], ['id'],
                          ondelete='SET NULL')
    op.create_foreign_key('sjob_scan_dns_id', 'scan_jobs', 'scan_dns', ['dns_check_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_users_last_login_id'), 'users', ['last_login_id'], unique=False)

    op.create_foreign_key('users_user_login_history_id', 'users', 'user_login_history', ['last_login_id'], ['id'],
                          ondelete='SET NULL')

    op.create_foreign_key('cert_alt_name_cert_id', 'certificate_alt_names', 'certificates', ['cert_id'], ['id'],
                          ondelete='CASCADE')

    op.create_foreign_key('domain_name_base_domain_id', 'domain_name', 'base_domain', ['top_domain_id'], ['id'],
                          ondelete='SET NULL')

    op.create_foreign_key('fk_email_news_user_email_news_id', 'email_news_user', 'email_news', ['email_news_id'],
                          ['id'], ondelete='CASCADE')

    op.create_foreign_key('fk_email_news_user_users_id', 'email_news_user', 'users', ['user_id'], ['id'],
                          ondelete='CASCADE')

    op.create_foreign_key('crtsh_input_base_domain_id', 'crtsh_input', 'base_domain', ['sld_id'], ['id'],
                          ondelete='SET NULL')

    op.create_foreign_key('crtsh_watch_input_id', 'crtsh_query', 'crtsh_input', ['input_id'], ['id'],
                          ondelete='SET NULL')

    op.create_foreign_key('crtsh_watch_watch_service_id', 'crtsh_query', 'watch_service', ['service_id'], ['id'],
                          ondelete='SET NULL')

    op.create_foreign_key('crtsh_watch_sub_target_id', 'crtsh_query', 'subdomain_watch_target', ['sub_watch_id'],
                          ['id'], ondelete='SET NULL')

    op.create_foreign_key('crtsh_watch_target_id', 'crtsh_query', 'watch_target', ['watch_id'], ['id'],
                          ondelete='SET NULL')

    op.create_foreign_key('fk_crtsh_query_results_crtsh_query_id', 'crtsh_query_results', 'crtsh_query', ['query_id'],
                          ['id'], ondelete='CASCADE')

    op.create_foreign_key('fk_ip_scan_record_watch_service_id', 'ip_scan_record', 'watch_service', ['service_id'],
                          ['id'], ondelete='SET NULL')

    op.create_foreign_key('fk_ip_scan_result_ip_scan_record_id', 'ip_scan_result', 'ip_scan_record',
                          ['ip_scan_record_id'], ['id'], ondelete='CASCADE')

    op.create_foreign_key('keychest_agent_organization_id', 'keychest_agent', 'organization', ['organization_id'],
                          ['id'], ondelete='CASCADE')

    op.create_foreign_key('organization_group_organization_id', 'organization_group', 'organization',
                          ['organization_id'], ['id'], ondelete='CASCADE')

    op.create_foreign_key('organization_group_organization_group_id', 'organization_group', 'organization_group',
                          ['parent_group_id'], ['id'], ondelete='SET NULL')

    op.create_foreign_key('dns_watch_target_id', 'scan_dns', 'watch_target', ['watch_id'], ['id'], ondelete='SET NULL')

    op.create_foreign_key('scan_dns_entry_scan_id', 'scan_dns_entry', 'scan_dns', ['scan_id'], ['id'],
                          ondelete='CASCADE')

    op.create_foreign_key('sgap_watch_target_id', 'scan_gaps', 'watch_target', ['watch_id'], ['id'],
                          ondelete='CASCADE')

    op.create_foreign_key('fk_scan_handshake_results_scan_handshakes_id', 'scan_handshake_results', 'scan_handshakes',
                          ['scan_id'], ['id'], ondelete='CASCADE')

    op.create_foreign_key('scan_handshakes_scan_sub_tls_id_ecc', 'scan_handshakes', 'scan_sub_tls', ['sub_ecc'], ['id'],
                          ondelete='SET NULL')

    op.create_foreign_key('scan_handshakes_scan_sub_tls_id_rsa', 'scan_handshakes', 'scan_sub_tls', ['sub_rsa'], ['id'],
                          ondelete='SET NULL')

    op.create_foreign_key('tls_watch_target_id', 'scan_handshakes', 'watch_target', ['watch_id'], ['id'],
                          ondelete='SET NULL')

    op.create_foreign_key('shist_watch_target_id', 'scan_history', 'watch_target', ['watch_id'], ['id'],
                          ondelete='CASCADE')

    op.create_foreign_key('scan_sub_tls_scan_handshakes_id', 'scan_sub_tls', 'scan_handshakes', ['parent_scan_id'],
                          ['id'], ondelete='SET NULL')

    op.create_foreign_key('scan_sub_tls_watch_target_id', 'scan_sub_tls', 'watch_target', ['watch_id'], ['id'],
                          ondelete='SET NULL')

    op.create_foreign_key('fk_scan_tls_desc_ip_address_id', 'scan_tls_desc', 'ip_address', ['ip_id'], ['id'],
                          ondelete='CASCADE')

    op.create_foreign_key('fk_scan_tls_desc_watch_service_id', 'scan_tls_desc', 'watch_service', ['sni_id'], ['id'],
                          ondelete='CASCADE')

    op.create_foreign_key('fk_scan_tls_desc_ext_scan_tls_desc_id', 'scan_tls_desc_ext', 'scan_tls_desc',
                          ['tls_desc_id'], ['id'], ondelete='CASCADE')

    op.create_foreign_key('fk_scan_tls_desc_ext_scan_tls_params_id', 'scan_tls_desc_ext', 'scan_tls_params',
                          ['tls_params_id'], ['id'], ondelete='CASCADE')

    op.create_foreign_key('fk_scan_web_app_scan_tls_desc_id', 'scan_web_app', 'scan_tls_desc', ['host_id'], ['id'],
                          ondelete='SET NULL')

    op.create_foreign_key('wa_sub_res_watch_target_id', 'subdomain_results', 'subdomain_watch_target', ['watch_id'],
                          ['id'], ondelete='CASCADE')

    op.create_foreign_key('subdom_watch_entry_subdomain_results_id_last', 'subdomain_watch_result_entry',
                          'subdomain_results', ['first_scan_id'], ['id'], ondelete='SET NULL')

    op.create_foreign_key('subdom_watch_entry_subdomain_results_id_first', 'subdomain_watch_result_entry',
                          'subdomain_results', ['last_scan_id'], ['id'], ondelete='SET NULL')

    op.create_foreign_key('subdom_watch_entry_service_id', 'subdomain_watch_result_entry', 'watch_service',
                          ['service_id'], ['id'], ondelete='CASCADE')

    op.create_foreign_key('subdom_watch_entry_watch_id', 'subdomain_watch_result_entry', 'subdomain_watch_target',
                          ['watch_id'], ['id'], ondelete='CASCADE')

    op.create_foreign_key('sub_wt_base_domain_id', 'subdomain_watch_target', 'base_domain', ['top_domain_id'], ['id'],
                          ondelete='SET NULL')

    op.create_foreign_key('fk_ip_scan_record_ip_scan_record_id', 'user_ip_scan_record', 'ip_scan_record',
                          ['ip_scan_record_id'], ['id'], ondelete='CASCADE')

    op.create_foreign_key('fk_user_ip_scan_record_users_id', 'user_ip_scan_record', 'users', ['user_id'], ['id'],
                          ondelete='CASCADE')

    op.create_foreign_key('user_login_history_users_id', 'user_login_history', 'users', ['user_id'], ['id'],
                          ondelete='CASCADE')

    op.create_foreign_key('wa_sub_users_id', 'user_subdomain_watch_target', 'users', ['user_id'], ['id'],
                          ondelete='CASCADE')

    op.create_foreign_key('wa_sub_watch_target_id', 'user_subdomain_watch_target', 'subdomain_watch_target',
                          ['watch_id'], ['id'], ondelete='CASCADE')

    op.create_foreign_key('wa_users_id', 'user_watch_target', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    op.create_foreign_key('wa_watch_target_id', 'user_watch_target', 'watch_target', ['watch_id'], ['id'],
                          ondelete='CASCADE')

    op.create_foreign_key('watch_local_service_keychest_agent_id', 'watch_local_service', 'keychest_agent',
                          ['agent_id'], ['id'], ondelete='CASCADE')

    op.create_foreign_key('watch_local_service_watch_service_id', 'watch_local_service', 'watch_service',
                          ['service_id'], ['id'], ondelete='CASCADE')

    op.create_foreign_key('fk_watch_service_crtsh_input_id', 'watch_service', 'crtsh_input', ['crtsh_input_id'], ['id'],
                          ondelete='SET NULL')

    op.create_foreign_key('watch_service_base_domain_id', 'watch_service', 'base_domain', ['top_domain_id'], ['id'],
                          ondelete='SET NULL')

    op.create_foreign_key('wt_keychest_agent_id', 'watch_target', 'keychest_agent', ['agent_id'], ['id'],
                          ondelete='CASCADE')

    op.create_foreign_key('wt_ip_scan_record_id', 'watch_target', 'ip_scan_record', ['ip_scan_id'], ['id'],
                          ondelete='SET NULL')

    op.create_foreign_key('wt_scan_dns_id', 'watch_target', 'scan_dns', ['last_dns_scan_id'], ['id'],
                          ondelete='SET NULL')

    op.create_foreign_key('wt_watch_service_id', 'watch_target', 'watch_service', ['service_id'], ['id'],
                          ondelete='SET NULL')

    op.create_foreign_key('wt_base_domain_id', 'watch_target', 'base_domain', ['top_domain_id'], ['id'],
                          ondelete='SET NULL')

    op.create_foreign_key('who_base_domain_id', 'whois_result', 'base_domain', ['domain_id'], ['id'],
                          ondelete='CASCADE')


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_user_login_history_id', 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_last_login_id'), table_name='users')
    op.drop_column(u'users', 'weekly_emails_disabled')
    op.drop_column(u'users', 'utc_offset')
    op.drop_column(u'users', 'timezone')
    op.drop_column(u'users', 'last_login_id')
    op.drop_column(u'users', 'last_login_at')
    op.drop_column(u'users', 'last_email_report_sent_at')
    op.drop_column(u'users', 'last_email_report_enqueued_at')
    op.drop_column(u'users', 'last_email_no_servers_sent_at')
    op.drop_column(u'users', 'last_action_at')
    op.drop_column(u'users', 'is_superadmin')
    op.drop_column(u'users', 'cur_login_at')
    op.drop_column(u'users', 'accredit_own')
    op.drop_column(u'users', 'accredit')
    op.drop_constraint('sjob_scan_dns_id', 'scan_jobs', type_='foreignkey')
    op.drop_constraint('sjob_whois_result_id', 'scan_jobs', type_='foreignkey')
    op.drop_constraint('sjob_crtsh_query_id', 'scan_jobs', type_='foreignkey')
    op.drop_index(op.f('ix_scan_jobs_whois_check_id'), table_name='scan_jobs')
    op.drop_index(op.f('ix_scan_jobs_dns_check_id'), table_name='scan_jobs')
    op.drop_index(op.f('ix_scan_jobs_crtsh_check_id'), table_name='scan_jobs')
    op.alter_column(u'scan_jobs', 'scan_host',
                    existing_type=mysql.VARCHAR(collation=u'utf8mb4_unicode_ci', length=191),
                    nullable=False)
    op.drop_column(u'scan_jobs', 'whois_check_id')
    op.drop_column(u'scan_jobs', 'scan_ip')
    op.drop_column(u'scan_jobs', 'dns_check_id')
    op.drop_column(u'scan_jobs', 'crtsh_checks')
    op.drop_column(u'scan_jobs', 'crtsh_check_id')
    op.drop_index(op.f('ix_whois_result_domain_id'), table_name='whois_result')
    op.drop_table('whois_result')
    op.drop_index(op.f('ix_watch_target_top_domain_id'), table_name='watch_target')
    op.drop_index(op.f('ix_watch_target_service_id'), table_name='watch_target')
    op.drop_index(op.f('ix_watch_target_last_dns_scan_id'), table_name='watch_target')
    op.drop_index(op.f('ix_watch_target_ip_scan_id'), table_name='watch_target')
    op.drop_index(op.f('ix_watch_target_agent_id'), table_name='watch_target')
    op.drop_table('watch_target')
    op.drop_index(op.f('ix_watch_service_top_domain_id'), table_name='watch_service')
    op.drop_index(op.f('ix_watch_service_crtsh_input_id'), table_name='watch_service')
    op.drop_table('watch_service')
    op.drop_index(op.f('ix_watch_local_service_service_id'), table_name='watch_local_service')
    op.drop_index(op.f('ix_watch_local_service_agent_id'), table_name='watch_local_service')
    op.drop_table('watch_local_service')
    op.drop_index(op.f('ix_user_watch_target_watch_id'), table_name='user_watch_target')
    op.drop_index(op.f('ix_user_watch_target_user_id'), table_name='user_watch_target')
    op.drop_table('user_watch_target')
    op.drop_index(op.f('ix_user_subdomain_watch_target_watch_id'), table_name='user_subdomain_watch_target')
    op.drop_index(op.f('ix_user_subdomain_watch_target_user_id'), table_name='user_subdomain_watch_target')
    op.drop_table('user_subdomain_watch_target')
    op.drop_index(op.f('ix_user_login_history_user_id'), table_name='user_login_history')
    op.drop_table('user_login_history')
    op.drop_index(op.f('ix_user_ip_scan_record_user_id'), table_name='user_ip_scan_record')
    op.drop_index(op.f('ix_user_ip_scan_record_ip_scan_record_id'), table_name='user_ip_scan_record')
    op.drop_table('user_ip_scan_record')
    op.drop_table('system_last_events')
    op.drop_index(op.f('ix_subdomain_watch_target_top_domain_id'), table_name='subdomain_watch_target')
    op.drop_table('subdomain_watch_target')
    op.drop_index(op.f('ix_subdomain_watch_result_entry_watch_id'), table_name='subdomain_watch_result_entry')
    op.drop_index(op.f('ix_subdomain_watch_result_entry_service_id'), table_name='subdomain_watch_result_entry')
    op.drop_index(op.f('ix_subdomain_watch_result_entry_name'), table_name='subdomain_watch_result_entry')
    op.drop_index(op.f('ix_subdomain_watch_result_entry_last_scan_id'), table_name='subdomain_watch_result_entry')
    op.drop_index(op.f('ix_subdomain_watch_result_entry_first_scan_id'), table_name='subdomain_watch_result_entry')
    op.drop_table('subdomain_watch_result_entry')
    op.drop_table('subdomain_scan_blacklist')
    op.drop_index(op.f('ix_subdomain_results_watch_id'), table_name='subdomain_results')
    op.drop_table('subdomain_results')
    op.drop_index(op.f('ix_scan_web_app_host_id'), table_name='scan_web_app')
    op.drop_table('scan_web_app')
    op.drop_table('scan_tls_params')
    op.drop_index(op.f('ix_scan_tls_desc_ext_tls_params_id'), table_name='scan_tls_desc_ext')
    op.drop_index(op.f('ix_scan_tls_desc_ext_tls_desc_id'), table_name='scan_tls_desc_ext')
    op.drop_table('scan_tls_desc_ext')
    op.drop_index(op.f('ix_scan_tls_desc_sni_id'), table_name='scan_tls_desc')
    op.drop_index(op.f('ix_scan_tls_desc_ip_id'), table_name='scan_tls_desc')
    op.drop_table('scan_tls_desc')
    op.drop_index(op.f('ix_scan_sub_tls_watch_id'), table_name='scan_sub_tls')
    op.drop_index(op.f('ix_scan_sub_tls_parent_scan_id'), table_name='scan_sub_tls')
    op.drop_table('scan_sub_tls')
    op.drop_index(op.f('ix_scan_history_watch_id'), table_name='scan_history')
    op.drop_table('scan_history')
    op.drop_index(op.f('ix_scan_handshakes_watch_id'), table_name='scan_handshakes')
    op.drop_index(op.f('ix_scan_handshakes_sub_rsa'), table_name='scan_handshakes')
    op.drop_index(op.f('ix_scan_handshakes_sub_ecc'), table_name='scan_handshakes')
    op.drop_table('scan_handshakes')
    op.drop_index(op.f('ix_scan_handshake_results_scan_id'), table_name='scan_handshake_results')
    op.drop_table('scan_handshake_results')
    op.drop_index(op.f('ix_scan_gaps_watch_id'), table_name='scan_gaps')
    op.drop_table('scan_gaps')
    op.drop_index(op.f('ix_scan_dns_entry_scan_id'), table_name='scan_dns_entry')
    op.drop_index(op.f('ix_scan_dns_entry_ip'), table_name='scan_dns_entry')
    op.drop_table('scan_dns_entry')
    op.drop_index(op.f('ix_scan_dns_watch_id'), table_name='scan_dns')
    op.drop_table('scan_dns')
    op.drop_index(op.f('ix_organization_group_parent_group_id'), table_name='organization_group')
    op.drop_index(op.f('ix_organization_group_organization_id'), table_name='organization_group')
    op.drop_table('organization_group')
    op.drop_table('organization')
    op.drop_index(op.f('ix_last_scan_cache_scan_type'), table_name='last_scan_cache')
    op.drop_index(op.f('ix_last_scan_cache_obj_id'), table_name='last_scan_cache')
    op.drop_table('last_scan_cache')
    op.drop_index(op.f('ix_keychest_agent_organization_id'), table_name='keychest_agent')
    op.drop_index(op.f('ix_keychest_agent_api_key'), table_name='keychest_agent')
    op.drop_table('keychest_agent')
    op.drop_index(op.f('ix_ip_scan_result_ip_scan_record_id'), table_name='ip_scan_result')
    op.drop_table('ip_scan_result')
    op.drop_index(op.f('ix_ip_scan_record_service_id'), table_name='ip_scan_record')
    op.drop_table('ip_scan_record')
    op.drop_table('ip_address')
    op.drop_index(op.f('ix_email_news_user_user_id'), table_name='email_news_user')
    op.drop_index(op.f('ix_email_news_user_email_news_id'), table_name='email_news_user')
    op.drop_table('email_news_user')
    op.drop_table('email_news')
    op.drop_index(op.f('ix_domain_name_top_domain_id'), table_name='domain_name')
    op.drop_table('domain_name')
    op.drop_index(op.f('ix_crtsh_query_results_query_id'), table_name='crtsh_query_results')
    op.drop_table('crtsh_query_results')
    op.drop_index(op.f('ix_crtsh_query_watch_id'), table_name='crtsh_query')
    op.drop_index(op.f('ix_crtsh_query_sub_watch_id'), table_name='crtsh_query')
    op.drop_index(op.f('ix_crtsh_query_service_id'), table_name='crtsh_query')
    op.drop_index(op.f('ix_crtsh_query_input_id'), table_name='crtsh_query')
    op.drop_table('crtsh_query')
    op.drop_index(op.f('ix_crtsh_input_sld_id'), table_name='crtsh_input')
    op.drop_table('crtsh_input')
    op.drop_index(op.f('ix_certificates_fprint_sha256'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_fprint_sha1'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_crt_sh_id'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_index(op.f('ix_certificate_alt_names_cert_id'), table_name='certificate_alt_names')
    op.drop_index(op.f('ix_certificate_alt_names_alt_name'), table_name='certificate_alt_names')
    op.drop_table('certificate_alt_names')
    op.drop_table('base_domain')
    op.drop_table('alembic_version_data')
    # ### end Alembic commands ###
