"""whois email

Revision ID: 07fb32f79807
Revises: fe71733c97a7
Create Date: 2017-06-22 09:36:15.136116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07fb32f79807'
down_revision = 'fe71733c97a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_jobs', sa.Column('crtsh_checks', sa.String(length=255), nullable=True))
    op.add_column('scan_jobs', sa.Column('dns_check_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_scan_jobs_dns_check_id'), 'scan_jobs', ['dns_check_id'], unique=False)
    op.create_foreign_key('scan_dns_id', 'scan_jobs', 'scan_dns', ['dns_check_id'], ['id'])
    op.add_column('whois_result', sa.Column('dnssec', sa.SmallInteger(), nullable=True))
    op.add_column('whois_result', sa.Column('emails', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whois_result', 'emails')
    op.drop_column('whois_result', 'dnssec')
    op.drop_constraint('scan_dns_id', 'scan_jobs', type_='foreignkey')
    op.drop_index(op.f('ix_scan_jobs_dns_check_id'), table_name='scan_jobs')
    op.drop_column('scan_jobs', 'dns_check_id')
    op.drop_column('scan_jobs', 'crtsh_checks')
    # ### end Alembic commands ###
