"""watcher watch status

Revision ID: 16c8ba3993f5
Revises: 2df33983b4af
Create Date: 2017-06-15 10:16:57.788464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16c8ba3993f5'
down_revision = '2df33983b4af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watch_target', sa.Column('last_scan_state', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watch_target', 'last_scan_state')
    # ### end Alembic commands ###
