"""040 api client req id

Revision ID: ecad8e444393
Revises: a7771c831cdc
Create Date: 2017-10-02 09:31:13.373277+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecad8e444393'
down_revision = 'a7771c831cdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_waiting', sa.Column('client_req_id', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_api_waiting_waiting_id'), 'api_waiting', ['waiting_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_waiting_waiting_id'), table_name='api_waiting')
    op.drop_column('api_waiting', 'client_req_id')
    # ### end Alembic commands ###
