"""041 keychecker stats

Revision ID: 5db281725401
Revises: ecad8e444393
Create Date: 2017-10-18 21:27:02.206026+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5db281725401'
down_revision = 'ecad8e444393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keychecker_stats',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('stat_id', sa.String(64), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stat_id', name='keychecker_stats_stat_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keychecker_stats')
    # ### end Alembic commands ###
