"""044 ssh keys

Revision ID: 47d998983ce2
Revises: 7d81e713a73e
Create Date: 2017-11-15 17:18:07.378592+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '47d998983ce2'
down_revision = '7d81e713a73e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ssh_keys',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('key_id', sa.String(length=64), nullable=True),
    sa.Column('pub_key', sa.Text(), nullable=True),
    sa.Column('priv_key', sa.Text(), nullable=True),
    sa.Column('bit_size', sa.Integer(), nullable=True),
    sa.Column('key_type', sa.SmallInteger(), nullable=True),
    sa.Column('storage_type', sa.SmallInteger(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=10, unsigned=True), nullable=True),
    sa.Column('rec_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='ssh_keys_users_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_id', name='ssh_keys_key_id')
    )
    op.create_index(op.f('ix_ssh_keys_user_id'), 'ssh_keys', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ssh_keys')
    # ### end Alembic commands ###
