"""042 host mgmt

Revision ID: b635323148a1
Revises: 5db281725401
Create Date: 2017-10-26 13:32:45.881535+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b635323148a1'
down_revision = '5db281725401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('managed_host_groups',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('group_name', sa.String(length=255), nullable=True),
                    sa.Column('group_desc', sa.Text(), nullable=True),
                    sa.Column('group_data', sa.Text(), nullable=True),
                    sa.Column('user_id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='managed_host_groups_users_id',
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('managed_hosts',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('host_name', sa.String(length=255), nullable=True),
                    sa.Column('host_addr', sa.String(length=255), nullable=True),
                    sa.Column('ssh_port', sa.Integer(), nullable=True),
                    sa.Column('host_desc', sa.Text(), nullable=True),
                    sa.Column('host_data', sa.Text(), nullable=True),
                    sa.Column('user_id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
                    sa.Column('agent_id', sa.BigInteger(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['agent_id'], ['keychest_agent.id'], name='managed_hosts_agent_id',
                                            ondelete='SET NULL'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='managed_hosts_users_id',
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_index(op.f('ix_managed_host_groups_user_id'), 'managed_host_groups', ['user_id'], unique=False)
    op.create_table('managed_host_to_groups',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('host_id', sa.BigInteger(), nullable=False),
                    sa.Column('group_id', sa.BigInteger(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['group_id'], ['managed_host_groups.id'],
                                            name='managed_host_to_groups_group_id', ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['host_id'], ['managed_hosts.id'], name='managed_host_to_groups_host_id',
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('host_id', 'group_id', name='uk_managed_host_to_groups_host_group')
                    )

    op.create_index(op.f('ix_managed_host_to_groups_group_id'), 'managed_host_to_groups', ['group_id'], unique=False)
    op.create_index(op.f('ix_managed_host_to_groups_host_id'), 'managed_host_to_groups', ['host_id'], unique=False)

    op.create_index(op.f('ix_managed_hosts_agent_id'), 'managed_hosts', ['agent_id'], unique=False)
    op.create_index(op.f('ix_managed_hosts_user_id'), 'managed_hosts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_managed_hosts_user_id'), table_name='managed_hosts')
    op.drop_index(op.f('ix_managed_hosts_agent_id'), table_name='managed_hosts')
    op.drop_table('managed_hosts')
    op.drop_index(op.f('ix_managed_host_to_groups_host_id'), table_name='managed_host_to_groups')
    op.drop_index(op.f('ix_managed_host_to_groups_group_id'), table_name='managed_host_to_groups')
    op.drop_table('managed_host_to_groups')
    op.drop_index(op.f('ix_managed_host_groups_user_id'), table_name='managed_host_groups')
    op.drop_table('managed_host_groups')
    # ### end Alembic commands ###
