"""047 ownership cleanup

Revision ID: e679346b130f
Revises: f7dcd0d26e39
Create Date: 2017-11-27 15:26:53.597137+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e679346b130f'
down_revision = 'f7dcd0d26e39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_watch_target')
    op.drop_table('user_subdomain_watch_target')
    op.drop_table('user_ip_scan_record')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certificates', 'is_ev')
    op.drop_column('certificates', 'is_cn_wildcard')
    op.drop_column('certificates', 'is_alt_wildcard')
    op.create_table('user_ip_scan_record',
    sa.Column('id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('ip_scan_record_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('disabled_at', mysql.DATETIME(), nullable=True),
    sa.Column('scan_periodicity', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('auto_fill_watches', mysql.SMALLINT(display_width=6), server_default=sa.text(u"'0'"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ip_scan_record_id'], [u'ip_scan_record.id'], name=u'fk_ip_scan_record_ip_scan_record_id', ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], name=u'fk_user_ip_scan_record_users_id', ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('user_subdomain_watch_target',
    sa.Column('id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('watch_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('disabled_at', mysql.DATETIME(), nullable=True),
    sa.Column('auto_scan_added_at', mysql.DATETIME(), nullable=True),
    sa.Column('scan_periodicity', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('scan_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('auto_fill_watches', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], name=u'wa_sub_users_id', ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['watch_id'], [u'subdomain_watch_target.id'], name=u'wa_sub_watch_target_id', ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('user_watch_target',
    sa.Column('id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('watch_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('scan_periodicity', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('scan_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('auto_scan_added_at', mysql.DATETIME(), nullable=True),
    sa.Column('disabled_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], name=u'wa_users_id', ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['watch_id'], [u'watch_target.id'], name=u'wa_watch_target_id', ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
