"""048 ev certificate fields

Revision ID: 389bbcaf5007
Revises: e679346b130f
Create Date: 2017-11-27 15:28:34.434048+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '389bbcaf5007'
down_revision = 'e679346b130f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates', sa.Column('is_alt_wildcard', sa.SmallInteger(), nullable=False))
    op.add_column('certificates', sa.Column('is_cn_wildcard', sa.SmallInteger(), nullable=False))
    op.add_column('certificates', sa.Column('is_ev', sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certificates', 'is_ev')
    op.drop_column('certificates', 'is_cn_wildcard')
    op.drop_column('certificates', 'is_alt_wildcard')
    # ### end Alembic commands ###
