"""051 cert new fields

Revision ID: f4dbd22d5c1d
Revises: 1d973942057b
Create Date: 2017-12-01 09:58:19.221496+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4dbd22d5c1d'
down_revision = '1d973942057b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates', sa.Column('alt_names_cnt', sa.Integer(), nullable=True))
    op.add_column('certificates', sa.Column('is_ov', sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certificates', 'is_ov')
    op.drop_column('certificates', 'alt_names_cnt')
    # ### end Alembic commands ###
