"""052 cert pricelist update

Revision ID: 255f759d4072
Revises: f4dbd22d5c1d
Create Date: 2017-12-04 09:06:03.290371+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '255f759d4072'
down_revision = 'f4dbd22d5c1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate_price_list', sa.Column('price_ov_wildcard', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certificate_price_list', 'price_ov_wildcard')
    # ### end Alembic commands ###
