"""022 email news

Revision ID: 92f94d35c47f
Revises: be7998442daa
Create Date: 2017-08-16 12:54:59.479671+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92f94d35c47f'
down_revision = 'be7998442daa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_news',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('schedule_at', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('disabled_at', sa.DateTime(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_news_user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.Column('email_news_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['email_news_id'], ['email_news.id'], name='fk_email_news_user_email_news_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_email_news_user_users_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_news_user_email_news_id'), 'email_news_user', ['email_news_id'], unique=False)
    op.create_index(op.f('ix_email_news_user_user_id'), 'email_news_user', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_news_user_user_id'), table_name='email_news_user')
    op.drop_index(op.f('ix_email_news_user_email_news_id'), table_name='email_news_user')
    op.drop_table('email_news_user')
    op.drop_table('email_news')
    # ### end Alembic commands ###
