"""021 user timezone last email

Revision ID: be7998442daa
Revises: 9a345012d5e3
Create Date: 2017-08-15 11:59:14.927931+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be7998442daa'
down_revision = '9a345012d5e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_email_report_sent_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_email_report_enqueued_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.String(length=191), nullable=True))
    op.add_column('users', sa.Column('utc_offset', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('is_superadmin', sa.SmallInteger(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('last_email_no_servers_sent_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('weekly_emails_disabled', sa.SmallInteger(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'utc_offset')
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'last_email_report_sent_at')
    op.drop_column('users', 'weekly_emails_disabled')
    op.drop_column('users', 'last_email_no_servers_sent_at')
    op.drop_column('users', 'last_email_report_enqueued_at')
    op.drop_column('users', 'is_superadmin')
    # ### end Alembic commands ###
