"""023 IP specific scan

Revision ID: 9de5461427bf
Revises: 92f94d35c47f
Create Date: 2017-08-21 12:32:12.800858+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9de5461427bf'
down_revision = '92f94d35c47f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_jobs', sa.Column('scan_ip', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_jobs', 'scan_ip')
    # ### end Alembic commands ###
