"""027 db2.0 entities

Revision ID: 32cbbd5953d8
Revises: 8c238ced739e
Create Date: 2017-08-24 13:54:19.209974+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '32cbbd5953d8'
down_revision = '8c238ced739e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_name',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('domain_name', sa.String(length=255), nullable=False),
                    sa.Column('top_domain_id', sa.BigInteger(), nullable=True),
                    sa.ForeignKeyConstraint(['top_domain_id'], ['base_domain.id'], name='domain_name_base_domain_id',
                                            ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('domain_name')
                    )

    op.create_index(op.f('ix_domain_name_top_domain_id'), 'domain_name', ['top_domain_id'], unique=False)
    op.create_table('ip_address',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('ip_addr', sa.String(length=255), nullable=False),
                    sa.Column('ip_type', sa.SmallInteger(), nullable=False, server_default='2'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('ip_addr')
                    )

    op.create_table('ip_scan_record',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('service_name', sa.String(length=255), nullable=False),
                    sa.Column('service_id', sa.BigInteger(), nullable=True),
                    sa.Column('ip_beg', sa.String(length=24), nullable=False),
                    sa.Column('ip_end', sa.String(length=24), nullable=False),
                    sa.Column('ip_beg_int', sa.BigInteger(), nullable=True),
                    sa.Column('ip_end_int', sa.BigInteger(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('last_scan_at', sa.DateTime(), nullable=True),
                    sa.Column('last_scan_state', sa.SmallInteger(), nullable=True),
                    sa.Column('num_scans', sa.Integer(), nullable=True, server_default='0'),
                    sa.ForeignKeyConstraint(['service_id'], ['watch_service.id'],
                                            name='fk_ip_scan_record_watch_service_id', ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_ip_scan_record_service_id'), 'ip_scan_record', ['service_id'], unique=False)

    op.create_table('ip_scan_result',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('ip_scan_record_id', sa.BigInteger(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('finished_at', sa.DateTime(), nullable=True),
                    sa.Column('duration', sa.BigInteger(), nullable=True),
                    sa.Column('last_scan_at', sa.DateTime(), nullable=True),
                    sa.Column('last_scan_state', sa.SmallInteger(), nullable=True),
                    sa.Column('num_scans', sa.Integer(), nullable=True, server_default='1'),
                    sa.Column('num_ips_alive', sa.Integer(), nullable=False, server_default='0'),
                    sa.Column('num_ips_found', sa.Integer(), nullable=False, server_default='0'),
                    sa.Column('ips_alive', sa.Text(), nullable=True),
                    sa.Column('ips_found', sa.Text(), nullable=True),
                    sa.ForeignKeyConstraint(['ip_scan_record_id'], ['ip_scan_record.id'],
                                            name='fk_ip_scan_result_ip_scan_record_id', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_ip_scan_result_ip_scan_record_id'), 'ip_scan_result', ['ip_scan_record_id'], unique=False)

    op.create_table('scan_tls_desc',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('ip_id', sa.BigInteger(), nullable=False),
                    sa.Column('sni_id', sa.BigInteger(), nullable=False),
                    sa.Column('scan_port', sa.Integer(), nullable=False, server_default='443'),
                    sa.ForeignKeyConstraint(['ip_id'], ['ip_address.id'], name='fk_scan_tls_desc_ip_address_id',
                                            ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['sni_id'], ['watch_service.id'], name='fk_scan_tls_desc_watch_service_id',
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('ip_id', 'sni_id', 'scan_port', name='uk_scan_tls_desc_unique')
                    )
    op.create_index(op.f('ix_scan_tls_desc_ip_id'), 'scan_tls_desc', ['ip_id'], unique=False)
    op.create_index(op.f('ix_scan_tls_desc_sni_id'), 'scan_tls_desc', ['sni_id'], unique=False)

    op.create_table('scan_tls_params',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('tls_ver', sa.String(length=16), nullable=True),
                    sa.Column('key_type', sa.SmallInteger(), nullable=True, server_default='0'),
                    sa.Column('cipersuite_set', sa.BigInteger(), nullable=True, server_default='0'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('tls_ver', 'key_type', 'cipersuite_set', name='uk_scan_tls_params_unique')
                    )

    op.create_table('scan_tls_desc_ext',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('tls_desc_id', sa.BigInteger(), nullable=False),
                    sa.Column('tls_params_id', sa.BigInteger(), nullable=False),
                    sa.ForeignKeyConstraint(['tls_desc_id'], ['scan_tls_desc.id'],
                                            name='fk_scan_tls_desc_ext_scan_tls_desc_id', ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['tls_params_id'], ['scan_tls_params.id'],
                                            name='fk_scan_tls_desc_ext_scan_tls_params_id', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('tls_desc_id', 'tls_params_id', name='uk_scan_tls_desc_ext_unique')
                    )
    op.create_index(op.f('ix_scan_tls_desc_ext_tls_desc_id'), 'scan_tls_desc_ext', ['tls_desc_id'], unique=False)
    op.create_index(op.f('ix_scan_tls_desc_ext_tls_params_id'), 'scan_tls_desc_ext', ['tls_params_id'], unique=False)

    op.create_table('scan_web_app',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('host_id', sa.BigInteger(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('last_scan_at', sa.DateTime(), nullable=True),
                    sa.Column('num_scans', sa.Integer(), nullable=True, server_default='1'),
                    sa.Column('req_https_result', sa.String(length=64), nullable=True),
                    sa.Column('follow_http_result', sa.String(length=64), nullable=True),
                    sa.Column('follow_https_result', sa.String(length=64), nullable=True),
                    sa.Column('follow_http_url', sa.String(length=255), nullable=True),
                    sa.Column('follow_https_url', sa.String(length=255), nullable=True),
                    sa.Column('hsts_present', sa.SmallInteger(), nullable=True, server_default='0'),
                    sa.Column('hsts_max_age', sa.BigInteger(), nullable=True),
                    sa.Column('hsts_include_subdomains', sa.SmallInteger(), nullable=True),
                    sa.Column('hsts_preload', sa.SmallInteger(), nullable=True),
                    sa.Column('pinning_present', sa.SmallInteger(), nullable=True, server_default='0'),
                    sa.Column('pinning_report_only', sa.SmallInteger(), nullable=True),
                    sa.Column('pinning_pins', sa.Text(), nullable=True),
                    sa.ForeignKeyConstraint(['host_id'], ['scan_tls_desc.id'], name='fk_scan_web_app_scan_tls_desc_id',
                                            ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_scan_web_app_host_id'), 'scan_web_app', ['host_id'], unique=False)

    op.create_table('user_ip_scan_record',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('user_id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
                    sa.Column('ip_scan_record_id', sa.BigInteger(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('disabled_at', sa.DateTime(), nullable=True),
                    sa.Column('scan_periodicity', sa.BigInteger(), nullable=True),
                    sa.Column('auto_fill_watches', sa.SmallInteger(), nullable=False, server_default='0'),
                    sa.ForeignKeyConstraint(['ip_scan_record_id'], ['ip_scan_record.id'],
                                            name='fk_ip_scan_record_ip_scan_record_id', ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_ip_scan_record_users_id',
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('user_id', 'ip_scan_record_id', name='uk_user_ip_scan_record_unique')
                    )
    op.create_index(op.f('ix_user_ip_scan_record_ip_scan_record_id'), 'user_ip_scan_record', ['ip_scan_record_id'],
                    unique=False)
    op.create_index(op.f('ix_user_ip_scan_record_user_id'), 'user_ip_scan_record', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_ip_scan_record_user_id'), table_name='user_ip_scan_record')
    op.drop_index(op.f('ix_user_ip_scan_record_ip_scan_record_id'), table_name='user_ip_scan_record')
    op.drop_index(op.f('ix_ip_scan_result_ip_scan_record_id'), table_name='ip_scan_result')
    op.drop_index(op.f('ix_ip_scan_record_service_id'), table_name='ip_scan_record')
    op.drop_table('ip_scan_result')
    op.drop_table('user_ip_scan_record')
    op.drop_table('ip_scan_record')
    op.drop_index(op.f('ix_scan_web_app_host_id'), table_name='scan_web_app')
    op.drop_table('scan_web_app')
    op.drop_index(op.f('ix_scan_tls_desc_ext_tls_params_id'), table_name='scan_tls_desc_ext')
    op.drop_index(op.f('ix_scan_tls_desc_ext_tls_desc_id'), table_name='scan_tls_desc_ext')
    op.drop_table('scan_tls_desc_ext')
    op.drop_table('scan_tls_params')
    op.drop_index(op.f('ix_scan_tls_desc_sni_id'), table_name='scan_tls_desc')
    op.drop_index(op.f('ix_scan_tls_desc_ip_id'), table_name='scan_tls_desc')
    op.drop_table('scan_tls_desc')
    op.drop_table('ip_address')
    op.drop_index(op.f('ix_domain_name_top_domain_id'), table_name='domain_name')
    op.drop_table('domain_name')
    # ### end Alembic commands ###
