"""038 user autocreate

Revision ID: ca9f16b7ecb2
Revises: 7fa70183953e
Create Date: 2017-09-25 11:26:25.951824+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca9f16b7ecb2'
down_revision = '7fa70183953e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auto_created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('verified_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('blocked_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('new_api_keys_state', sa.SmallInteger(), nullable=False, server_default='0'))
    op.add_column('api_keys', sa.Column('api_verify_token', sa.String(length=24), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verified_at')
    op.drop_column('users', 'auto_created_at')
    op.drop_column('users', 'blocked_at')
    op.drop_column('users', 'new_api_keys_state')
    op.drop_column('api_keys', 'api_verify_token')
    # ### end Alembic commands ###
