"""049 issuer org

Revision ID: a2d90960dfdd
Revises: 389bbcaf5007
Create Date: 2017-11-28 08:31:49.561563+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2d90960dfdd'
down_revision = '389bbcaf5007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates', sa.Column('issuer_o', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certificates', 'issuer_o')
    # ### end Alembic commands ###
