"""054 cdn fields added to scan

Revision ID: cdf765c6d33b
Revises: 92ca643c1ad8
Create Date: 2017-12-05 18:41:52.738955+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf765c6d33b'
down_revision = '92ca643c1ad8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_handshakes', sa.Column('cdn_cname', sa.String(length=255), nullable=True))
    op.add_column('scan_handshakes', sa.Column('cdn_headers', sa.String(length=255), nullable=True))
    op.add_column('scan_handshakes', sa.Column('cdn_reverse', sa.String(length=255), nullable=True))
    op.add_column('scan_handshakes', sa.Column('ip_scanned_reverse', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_handshakes', 'ip_scanned_reverse')
    op.drop_column('scan_handshakes', 'cdn_reverse')
    op.drop_column('scan_handshakes', 'cdn_headers')
    op.drop_column('scan_handshakes', 'cdn_cname')
    # ### end Alembic commands ###
