"""whois tables

Revision ID: 3201db89dfa1
Revises: 2f5ddc3ac5c7
Create Date: 2017-06-15 18:22:32.222663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3201db89dfa1'
down_revision = '2f5ddc3ac5c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_domain',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_name')
    )
    op.create_table('whois_result',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('domain_id', sa.BigInteger(), nullable=False),
    sa.Column('registrant_cc', sa.String(length=255), nullable=True),
    sa.Column('registrar', sa.String(length=255), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('rec_updated_at', sa.DateTime(), nullable=True),
    sa.Column('dns', sa.Text(), nullable=True),
    sa.Column('aux', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_scan_at', sa.DateTime(), nullable=True),
    sa.Column('num_scans', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['base_domain.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whois_result_domain_id'), 'whois_result', ['domain_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whois_result_domain_id'), table_name='whois_result')
    op.drop_table('whois_result')
    op.drop_table('base_domain')
    # ### end Alembic commands ###
