"""016 foreign key add

Revision ID: 559df3a9366b
Revises: 28d21378e17b
Create Date: 2017-07-11 09:56:38.386689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '559df3a9366b'
down_revision = '28d21378e17b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('cert_alt_name_cert_id', 'certificate_alt_names', 'certificates', ['cert_id'], ['id'], ondelete='CASCADE')

    op.create_index(op.f('ix_crtsh_query_results_query_id'), 'crtsh_query_results', ['query_id'], unique=False)
    op.create_foreign_key('fk_crtsh_query_results_crtsh_query_id', 'crtsh_query_results', 'crtsh_query', ['query_id'], ['id'], ondelete='CASCADE')

    op.create_index(op.f('ix_scan_handshake_results_scan_id'), 'scan_handshake_results', ['scan_id'], unique=False)
    op.create_foreign_key('fk_scan_handshake_results_scan_handshakes_id', 'scan_handshake_results', 'scan_handshakes', ['scan_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_scan_handshake_results_scan_handshakes_id', 'scan_handshake_results', type_='foreignkey')
    op.drop_index(op.f('ix_scan_handshake_results_scan_id'), table_name='scan_handshake_results')
    op.drop_constraint('fk_crtsh_query_results_crtsh_query_id', 'crtsh_query_results', type_='foreignkey')
    op.drop_index(op.f('ix_crtsh_query_results_query_id'), table_name='crtsh_query_results')
    op.drop_constraint('cert_alt_name_cert_id', 'certificate_alt_names', type_='foreignkey')
    # ### end Alembic commands ###
