"""scan job whois

Revision ID: 68793266cf2c
Revises: 74e916f7cfec
Create Date: 2017-06-16 19:17:47.633375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68793266cf2c'
down_revision = '74e916f7cfec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_jobs', sa.Column('whois_check_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_scan_jobs_whois_check_id'), 'scan_jobs', ['whois_check_id'], unique=False)
    op.create_foreign_key(None, 'scan_jobs', 'whois_result', ['whois_check_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scan_jobs', type_='foreignkey')
    op.drop_index(op.f('ix_scan_jobs_whois_check_id'), table_name='scan_jobs')
    op.drop_column('scan_jobs', 'whois_check_id')
    # ### end Alembic commands ###
