"""crtsh watch

Revision ID: 74e916f7cfec
Revises: 6a1c9bf60d3f
Create Date: 2017-06-16 15:51:19.468031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74e916f7cfec'
down_revision = '6a1c9bf60d3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crtsh_query', sa.Column('last_scan_at', sa.DateTime(), nullable=True))
    op.add_column('crtsh_query', sa.Column('num_scans', sa.Integer(), nullable=True))
    op.add_column('crtsh_query', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('crtsh_query', sa.Column('watch_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_crtsh_query_watch_id'), 'crtsh_query', ['watch_id'], unique=False)
    op.create_foreign_key(None, 'crtsh_query', 'watch_target', ['watch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'crtsh_query', type_='foreignkey')
    op.drop_index(op.f('ix_crtsh_query_watch_id'), table_name='crtsh_query')
    op.drop_column('crtsh_query', 'watch_id')
    op.drop_column('crtsh_query', 'updated_at')
    op.drop_column('crtsh_query', 'num_scans')
    op.drop_column('crtsh_query', 'last_scan_at')
    # ### end Alembic commands ###
