"""periodic scanner baseline

Revision ID: 8977a15fce13
Revises: 3201db89dfa1
Create Date: 2017-06-15 19:07:07.322094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8977a15fce13'
down_revision = '3201db89dfa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('last_record_cache',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('record_key', sa.String(length=191), nullable=False),
    sa.Column('record_at', sa.DateTime(), nullable=True),
    sa.Column('record_id', sa.BigInteger(), nullable=True),
    sa.Column('record_aux', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_key')
    )
    op.create_table('system_last_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_key', sa.String(length=191), nullable=False),
    sa.Column('event_at', sa.DateTime(), nullable=True),
    sa.Column('aux', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key')
    )
    op.create_table('scan_gaps',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('watch_id', sa.BigInteger(), nullable=True),
    sa.Column('scan_code', sa.SmallInteger(), nullable=False),
    sa.Column('scan_type', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('gap_start', sa.DateTime(), nullable=True),
    sa.Column('gap_end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['watch_id'], ['watch_target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_gaps_watch_id'), 'scan_gaps', ['watch_id'], unique=False)
    op.create_table('scan_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('watch_id', sa.BigInteger(), nullable=True),
    sa.Column('scan_code', sa.SmallInteger(), nullable=False),
    sa.Column('scan_type', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['watch_id'], ['watch_target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_history_watch_id'), 'scan_history', ['watch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_history_watch_id'), table_name='scan_history')
    op.drop_table('scan_history')
    op.drop_index(op.f('ix_scan_gaps_watch_id'), table_name='scan_gaps')
    op.drop_table('scan_gaps')
    op.drop_table('system_last_events')
    op.drop_table('last_record_cache')
    # ### end Alembic commands ###
