"""008 agents

Revision ID: 95f544022400
Revises: 2cac1bf932e8
Create Date: 2017-07-09 17:48:56.982882

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '95f544022400'
down_revision = '2cac1bf932e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('name', sa.String(length=191), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('keychest_agent',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('name', sa.String(length=191), nullable=False),
                    sa.Column('api_key', sa.String(length=191), nullable=False),
                    sa.Column('organization_id', sa.BigInteger(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('last_seen_active_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'],
                                            name='keychest_agent_organization_id', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_keychest_agent_organization_id'), 'keychest_agent', ['organization_id'], unique=False)

    op.create_table('organization_group',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('name', sa.String(length=191), nullable=False),
                    sa.Column('organization_id', sa.BigInteger(), nullable=False),
                    sa.Column('parent_group_id', sa.BigInteger(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'],
                                            name='organization_group_organization_id', ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['parent_group_id'], ['organization_group.id'],
                                            name='organization_group_organization_group_id', ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_organization_group_organization_id'), 'organization_group', ['organization_id'],
                    unique=False)
    op.create_index(op.f('ix_organization_group_parent_group_id'), 'organization_group', ['parent_group_id'],
                    unique=False)

    op.create_table('watch_service',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('service_name', sa.String(length=255), nullable=False),
                    sa.Column('top_domain_id', sa.BigInteger(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('last_scan_at', sa.DateTime(), nullable=True),
                    sa.Column('last_scan_state', sa.SmallInteger(), nullable=True),
                    sa.ForeignKeyConstraint(['top_domain_id'], ['base_domain.id'], name='watch_service_base_domain_id',
                                            ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_watch_service_top_domain_id'), 'watch_service', ['top_domain_id'], unique=False)

    op.create_table('watch_local_service',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('service_id', sa.BigInteger(), nullable=False),
                    sa.Column('agent_id', sa.BigInteger(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['agent_id'], ['keychest_agent.id'],
                                            name='watch_local_service_keychest_agent_id', ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['service_id'], ['watch_service.id'],
                                            name='watch_local_service_watch_service_id', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_watch_local_service_agent_id'), 'watch_local_service', ['agent_id'], unique=False)
    op.create_index(op.f('ix_watch_local_service_service_id'), 'watch_local_service', ['service_id'], unique=False)
    op.add_column(u'subdomain_watch_result_entry', sa.Column('service_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_subdomain_watch_result_entry_service_id'), 'subdomain_watch_result_entry', ['service_id'],
                    unique=False)
    op.create_foreign_key('subdom_watch_entry_service_id', 'subdomain_watch_result_entry', 'watch_service',
                          ['service_id'], ['id'], ondelete='CASCADE')
    op.add_column(u'watch_target', sa.Column('agent_id', sa.BigInteger(), nullable=True))
    op.add_column(u'watch_target', sa.Column('service_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_watch_target_agent_id'), 'watch_target', ['agent_id'], unique=False)
    op.create_index(op.f('ix_watch_target_service_id'), 'watch_target', ['service_id'], unique=False)
    op.create_foreign_key('wt_keychest_agent_id', 'watch_target', 'keychest_agent', ['agent_id'], ['id'],
                          ondelete='CASCADE')
    op.create_foreign_key('wt_watch_service_id', 'watch_target', 'watch_service', ['service_id'], ['id'],
                          ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('wt_watch_service_id', 'watch_target', type_='foreignkey')
    op.drop_constraint('wt_keychest_agent_id', 'watch_target', type_='foreignkey')
    op.drop_index(op.f('ix_watch_target_service_id'), table_name='watch_target')
    op.drop_index(op.f('ix_watch_target_agent_id'), table_name='watch_target')
    op.drop_column(u'watch_target', 'service_id')
    op.drop_column(u'watch_target', 'agent_id')
    op.drop_constraint('subdom_watch_entry_service_id', 'subdomain_watch_result_entry', type_='foreignkey')
    op.drop_index(op.f('ix_subdomain_watch_result_entry_service_id'), table_name='subdomain_watch_result_entry')
    op.drop_column(u'subdomain_watch_result_entry', 'service_id')
    op.drop_index(op.f('ix_watch_local_service_service_id'), table_name='watch_local_service')
    op.drop_index(op.f('ix_watch_local_service_agent_id'), table_name='watch_local_service')
    op.drop_table('watch_local_service')
    op.drop_index(op.f('ix_watch_service_top_domain_id'), table_name='watch_service')
    op.drop_table('watch_service')
    op.drop_index(op.f('ix_organization_group_parent_group_id'), table_name='organization_group')
    op.drop_index(op.f('ix_organization_group_organization_id'), table_name='organization_group')
    op.drop_table('organization_group')
    op.drop_index(op.f('ix_keychest_agent_organization_id'), table_name='keychest_agent')
    op.drop_table('keychest_agent')
    op.drop_table('organization')
    # ### end Alembic commands ###
