"""012 denormalized last scans

Revision ID: 99b3bef9ff03
Revises: 41339a2c71f7
Create Date: 2017-07-10 12:56:32.886116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99b3bef9ff03'
down_revision = '41339a2c71f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('last_scan_cache',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cache_type', sa.SmallInteger(), nullable=False),
    sa.Column('obj_id', sa.BigInteger(), nullable=True),
    sa.Column('scan_type', sa.Integer(), nullable=False),
    sa.Column('scan_sub_type', sa.Integer(), nullable=False),
    sa.Column('aux_key', sa.String(length=191), nullable=False),
    sa.Column('scan_id', sa.BigInteger(), nullable=False),
    sa.Column('scan_aux', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_type', 'obj_id', 'scan_type', 'scan_sub_type', 'aux_key', name='uq_last_scan_cache_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('last_scan_cache')
    # ### end Alembic commands ###
