"""009 subtls scan

Revision ID: 9a285012d5e3
Revises: 9a280012d5e3
Create Date: 2017-07-09 18:01:40.376736

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9a285012d5e3'
down_revision = '9a280012d5e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_sub_tls',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('job_id', sa.BigInteger(), nullable=True),
                    sa.Column('watch_id', sa.BigInteger(), nullable=True),
                    sa.Column('parent_scan_id', sa.BigInteger(), nullable=True),
                    sa.Column('ip_scanned', sa.String(length=255), nullable=True),
                    sa.Column('is_ipv6', sa.SmallInteger(), nullable=False),
                    sa.Column('tls_ver', sa.String(length=16), nullable=True),
                    sa.Column('key_type', sa.SmallInteger(), nullable=True),
                    sa.Column('cipersuite_set', sa.BigInteger(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('last_scan_at', sa.DateTime(), nullable=True),
                    sa.Column('num_scans', sa.Integer(), nullable=True),
                    sa.Column('status', sa.SmallInteger(), nullable=True),
                    sa.Column('err_code', sa.SmallInteger(), nullable=True),
                    sa.Column('tls_alert_code', sa.Integer(), nullable=True),
                    sa.Column('time_elapsed', sa.Integer(), nullable=True),
                    sa.Column('results', sa.Integer(), nullable=True),
                    sa.Column('new_results', sa.Integer(), nullable=True),
                    sa.Column('certs_ids', sa.Text(), nullable=True),
                    sa.Column('cert_id_leaf', sa.BigInteger(), nullable=True),
                    sa.Column('valid_path', sa.SmallInteger(), nullable=True),
                    sa.Column('valid_hostname', sa.SmallInteger(), nullable=True),
                    sa.Column('err_validity', sa.String(length=64), nullable=True),
                    sa.Column('err_many_leafs', sa.SmallInteger(), nullable=True),
                    sa.Column('err_valid_ossl_code', sa.Integer(), nullable=True),
                    sa.Column('err_valid_ossl_depth', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['parent_scan_id'], ['scan_handshakes.id'],
                                            name='scan_sub_tls_scan_handshakes_id', ondelete='SET NULL'),
                    sa.ForeignKeyConstraint(['watch_id'], ['watch_target.id'], name='scan_sub_tls_watch_target_id',
                                            ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_scan_sub_tls_parent_scan_id'), 'scan_sub_tls', ['parent_scan_id'], unique=False)
    op.create_index(op.f('ix_scan_sub_tls_watch_id'), 'scan_sub_tls', ['watch_id'], unique=False)

    op.add_column('scan_handshakes', sa.Column('sub_ecc', sa.BigInteger(), nullable=True))
    op.add_column('scan_handshakes', sa.Column('sub_rsa', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_scan_handshakes_sub_ecc'), 'scan_handshakes', ['sub_ecc'], unique=False)
    op.create_index(op.f('ix_scan_handshakes_sub_rsa'), 'scan_handshakes', ['sub_rsa'], unique=False)
    op.create_foreign_key('scan_handshakes_scan_sub_tls_id_rsa', 'scan_handshakes', 'scan_sub_tls', ['sub_rsa'], ['id'],
                          ondelete='SET NULL')
    op.create_foreign_key('scan_handshakes_scan_sub_tls_id_ecc', 'scan_handshakes', 'scan_sub_tls', ['sub_ecc'], ['id'],
                          ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('scan_handshakes_scan_sub_tls_id_ecc', 'scan_handshakes', type_='foreignkey')
    op.drop_constraint('scan_handshakes_scan_sub_tls_id_rsa', 'scan_handshakes', type_='foreignkey')
    op.drop_constraint('scan_sub_tls_scan_handshakes_id', 'scan_sub_tls', type_='foreignkey')
    op.drop_constraint('scan_sub_tls_watch_target_id', 'scan_sub_tls', type_='foreignkey')
    op.drop_index(op.f('ix_scan_handshakes_sub_rsa'), table_name='scan_handshakes')
    op.drop_index(op.f('ix_scan_handshakes_sub_ecc'), table_name='scan_handshakes')
    op.drop_column('scan_handshakes', 'sub_rsa')
    op.drop_column('scan_handshakes', 'sub_ecc')
    op.drop_index(op.f('ix_scan_sub_tls_watch_id'), table_name='scan_sub_tls')
    op.drop_index(op.f('ix_scan_sub_tls_parent_scan_id'), table_name='scan_sub_tls')
    op.drop_table('scan_sub_tls')
    # ### end Alembic commands ###
