"""017 last scan cache indices

Revision ID: 9a330012d5e3
Revises: 9a325012d5e3
Create Date: 2017-07-12 01:52:53.613858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a330012d5e3'
down_revision = '9a325012d5e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_last_scan_cache_obj_id'), 'last_scan_cache', ['obj_id'], unique=False)
    op.create_index(op.f('ix_last_scan_cache_scan_type'), 'last_scan_cache', ['scan_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_last_scan_cache_scan_type'), table_name='last_scan_cache')
    op.drop_index(op.f('ix_last_scan_cache_obj_id'), table_name='last_scan_cache')
    # ### end Alembic commands ###
