"""019 subdomain num res

Revision ID: 9a340012d5e3
Revises: 9a335012d5e3
Create Date: 2017-07-12 17:24:30.084624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a340012d5e3'
down_revision = '9a335012d5e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subdomain_results', sa.Column('result_size', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subdomain_results', 'result_size')
    # ### end Alembic commands ###
