"""020 synthetic DNS

Revision ID: 9a345012d5e3
Revises: 9a340012d5e3
Create Date: 2017-08-03 09:28:31.525223

"""
from alembic import op
from alembic import context

import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.dialects.mysql import INTEGER
from sqlalchemy import event, UniqueConstraint, orm
from sqlalchemy import Column, DateTime, String, Integer, ForeignKey, func, BLOB, Text, BigInteger, SmallInteger
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, Session as BaseSession, relationship, scoped_session

import logging
import sys
import pkg_resources
from keychest import util
from keychest import util_cert
from keychest.tls_domain_tools import TlsDomainTools
from keychest.dbutil import DbHelper, ResultModelUpdater
from keychest.consts import IpType


# revision identifiers, used by Alembic.
revision = '9a345012d5e3'
down_revision = '9a340012d5e3'
branch_labels = None
depends_on = None


Base = declarative_base()
logger = logging.getLogger(__name__)


class DbWatchTarget(Base):
    __tablename__ = 'watch_target'
    id = Column(BigInteger, primary_key=True)
    scan_host = Column(String(255), nullable=False)
    is_ip_host = Column(SmallInteger, default=0)  # watch target specified with IP


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_dns', sa.Column('is_synthetic', sa.SmallInteger(), nullable=False, server_default='0'))
    op.add_column('watch_target', sa.Column('is_ip_host', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###

    if context.is_offline_mode():
        logger.warning('Data migration skipped in the offline mode')
        return

    bind = op.get_bind()
    sess = scoped_session(sessionmaker(bind=bind))

    q = sess.query(DbWatchTarget)
    for idx, cur in enumerate(DbHelper.yield_limit(q, DbWatchTarget.id)):  # type: DbWatchTarget
        try:
            cur.is_ip_host = TlsDomainTools.get_ip_type(cur.scan_host)

        except Exception as ex:
            logger.warning('Exception in DbWatchTarget is_ip_host migration: %s' % ex)
    sess.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watch_target', 'is_ip_host')
    op.drop_column('scan_dns', 'is_synthetic')
    # ### end Alembic commands ###
