"""watcher whois domain

Revision ID: a0e14021f8c7
Revises: 07fb32f79807
Create Date: 2017-06-24 13:16:49.147048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0e14021f8c7'
down_revision = '07fb32f79807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watch_target', sa.Column('top_domain_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_watch_target_top_domain_id'), 'watch_target', ['top_domain_id'], unique=False)
    op.create_foreign_key('base_domain_id', 'watch_target', 'base_domain', ['top_domain_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('base_domain_id', 'watch_target', type_='foreignkey')
    op.drop_index(op.f('ix_watch_target_top_domain_id'), table_name='watch_target')
    op.drop_column('watch_target', 'top_domain_id')
    # ### end Alembic commands ###
