"""Initial revision

Revision ID: b1b133e9c186
Revises: 
Create Date: 2017-06-15 09:33:27.767187

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1b133e9c186'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('certificates', 'is_precert',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=False,
               existing_server_default=sa.text(u"'0'"))
    op.alter_column('certificates', 'is_precert_ca',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=False,
               existing_server_default=sa.text(u"'0'"))
    op.alter_column('scan_jobs', 'scan_host',
               existing_type=mysql.VARCHAR(collation=u'utf8mb4_unicode_ci', length=191),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scan_jobs', 'scan_host',
               existing_type=mysql.VARCHAR(collation=u'utf8mb4_unicode_ci', length=191),
               nullable=False)
    op.alter_column('certificates', 'is_precert_ca',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=True,
               existing_server_default=sa.text(u"'0'"))
    op.alter_column('certificates', 'is_precert',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=True,
               existing_server_default=sa.text(u"'0'"))
    # ### end Alembic commands ###
