"""017 last scan cache indices

Revision ID: d1d828103f3b
Revises: 559df3a9366b
Create Date: 2017-07-12 01:52:53.613858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1d828103f3b'
down_revision = '559df3a9366b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_last_scan_cache_obj_id'), 'last_scan_cache', ['obj_id'], unique=False)
    op.create_index(op.f('ix_last_scan_cache_scan_type'), 'last_scan_cache', ['scan_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_last_scan_cache_scan_type'), table_name='last_scan_cache')
    op.drop_index(op.f('ix_last_scan_cache_obj_id'), table_name='last_scan_cache')
    # ### end Alembic commands ###
