"""005 alembic data table

Revision ID: f2a93968cdc5
Revises: 7260f851fc2e
Create Date: 2017-07-06 20:31:29.569271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2a93968cdc5'
down_revision = '7260f851fc2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version_data',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('schema_ver', sa.BigInteger(), nullable=True),
    sa.Column('data_ver', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_version_data')
    # ### end Alembic commands ###
