"""tls scan res fix

Revision ID: fe71733c97a7
Revises: a54d95da0d80
Create Date: 2017-06-19 11:26:43.593979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe71733c97a7'
down_revision = 'a54d95da0d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scan_handshakes', 'err_validity',
                    existing_type=mysql.VARCHAR(collation=u'utf8mb4_unicode_ci', length=64),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scan_handshakes', 'err_validity',
                    existing_type=mysql.VARCHAR(collation=u'utf8mb4_unicode_ci', length=64),
                    nullable=True,
                    existing_server_default=sa.text(u"'0'"))
    # ### end Alembic commands ###
